apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage

      - alert: InstanceDown
        # Condition for alerting
        expr: up == 0
        for: 20s
        # Annotation - additional informational labels to store more information
        annotations:
          title: 'Instance {{ $labels.instance }} down'
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
          adaptations: '{"create_pod":{"name":"pod01","image":"nginx","namespace":"default","hosts":{"node":{"operator":"In","values":["worker-2","worker-11"]},"layer":{"operator":"In","values":["fog"]}}}}'
        # Labels - additional labels to be attached to the alert
        labels:
          severity: 'critical'
          actions: 'all'
